build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 80
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10
  NestedBlockDepth:
    active: true
    threshold: 5

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludeCommentStatements: true
  WildcardImport:
    active: true
  UnusedPrivateMember:
    active: true
  MagicNumber:
    active: false

formatting:
  active: false

naming:
  active: true
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    active: true
    variablePattern: '[a-z][A-Za-z0-9]*'

potential-bugs:
  active: true
  EqualsWithHashCodeExist:
    active: true
  UnsafeCallOnNullableType:
    active: true
  UnreachableCode:
    active: true