name: CI with Gradle

on:
  push:
    branches:
      [ "main", "dev" ]
  pull_request:
    branches:
      [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Build Gradle
        run: ./gradlew build


